export const MOCK_CATS = [
  {
    id: '1',
    name: 'Whiskers',
    class: 'Mage',
    classLevel: 3,
    room: 'Library',
    status: 'active',
    age: 12,
    gender: 'F',
    spriteId: 'female12',
    stats:      { STR: 3, DEX: 7, CON: 5, INT: 10, SPD: 6, CHA: 4, LUCK: 8 },
    bonusStats: { STR: 0, DEX: 1, CON: 0, INT: 2,  SPD: 0, CHA: 1, LUCK: 0 },
    abilities: ['Fireball', 'Blink', 'ManaShield'],
    mutations: ['GlowingEyes', 'ExtraTail'],
  },
  {
    id: '2',
    name: 'Brutus',
    class: 'Warrior',
    classLevel: 5,
    room: 'Barracks',
    status: 'active',
    age: 6,
    gender: 'M',
    spriteId: 'male03',
    stats:      { STR: 12, DEX: 4, CON: 11, INT: 2,  SPD: 5, CHA: 3, LUCK: 3 },
    bonusStats: { STR: 2,  DEX: 0, CON: 1,  INT: 0,  SPD: 0, CHA: 0, LUCK: 0 },
    abilities: ['Slash', 'Taunt', 'Fortify'],
    mutations: ['IronFur'],
  },
  {
    id: '3',
    name: 'Shadow',
    class: 'Rogue',
    classLevel: 4,
    room: 'Library',
    status: 'retired',
    age: 20,
    gender: 'M',
    spriteId: 'male07',
    stats:      { STR: 6, DEX: 13, CON: 4, INT: 5, SPD: 11, CHA: 6, LUCK: 9 },
    bonusStats: { STR: 0, DEX: 2,  CON: 0, INT: 0, SPD: 1,  CHA: 0, LUCK: 1 },
    abilities: ['Backstab', 'SmokeBomb', 'Blink'],
    mutations: ['GlowingEyes', 'PhaseShift'],
  },
  {
    id: '4',
    name: 'Luna',
    class: 'Cleric',
    classLevel: 2,
    room: 'Chapel',
    status: 'active',
    age: 8,
    gender: 'F',
    spriteId: 'female05',
    stats:      { STR: 4, DEX: 6, CON: 8, INT: 9, SPD: 5, CHA: 10, LUCK: 12 },
    bonusStats: { STR: 0, DEX: 0, CON: 1, INT: 1, SPD: 0, CHA: 2,  LUCK: 1  },
    abilities: ['Heal', 'HolyLight', 'Resurrect'],
    mutations: ['AngelWings', 'Halo'],
  },
  {
    id: '5',
    name: 'Grim',
    class: 'Necromancer',
    classLevel: 6,
    room: 'Crypt',
    status: 'active',
    age: 15,
    gender: 'M',
    spriteId: 'male11',
    stats:      { STR: 5, DEX: 5, CON: 3, INT: 13, SPD: 4, CHA: 5, LUCK: 6 },
    bonusStats: { STR: 0, DEX: 0, CON: 0, INT: 3,  SPD: 0, CHA: 0, LUCK: 1 },
    abilities: ['RaiseDead', 'SoulDrain', 'Curse'],
    mutations: ['HollowEyes', 'BoneClaws'],
  },
  {
    id: '6',
    name: 'Patches',
    class: 'Rogue',
    classLevel: 2,
    room: 'Barracks',
    status: 'active',
    age: 4,
    gender: 'F',
    spriteId: 'female08',
    stats:      { STR: 7, DEX: 11, CON: 6, INT: 4, SPD: 10, CHA: 7, LUCK: 10 },
    bonusStats: { STR: 0, DEX: 1,  CON: 0, INT: 0, SPD: 1,  CHA: 0, LUCK: 0  },
    abilities: ['Backstab', 'Pickpocket'],
    mutations: ['PhaseShift'],
  },
  {
    id: '7',
    name: 'Ember',
    class: 'Mage',
    classLevel: 7,
    room: 'Library',
    status: 'dead',
    age: 25,
    gender: 'F',
    spriteId: 'female02',
    stats:      { STR: 2, DEX: 8, CON: 2, INT: 14, SPD: 7, CHA: 5, LUCK: 7 },
    bonusStats: { STR: 0, DEX: 1, CON: 0, INT: 4,  SPD: 0, CHA: 0, LUCK: 1 },
    abilities: ['Fireball', 'Meteor', 'Blink'],
    mutations: ['GlowingEyes', 'FlameFur', 'ExtraTail'],
  },
  {
    id: '8',
    name: 'Tank',
    class: 'Warrior',
    classLevel: 8,
    room: 'Barracks',
    status: 'active',
    age: 9,
    gender: 'M',
    spriteId: 'male01',
    stats:      { STR: 14, DEX: 2, CON: 15, INT: 1, SPD: 3, CHA: 2, LUCK: 2 },
    bonusStats: { STR: 3,  DEX: 0, CON: 2,  INT: 0, SPD: 0, CHA: 0, LUCK: 0 },
    abilities: ['ShieldBash', 'Taunt', 'Fortify'],
    mutations: ['IronFur', 'StoneSkin'],
  },
  {
    id: '9',
    name: 'Zephyr',
    class: 'Ranger',
    classLevel: 3,
    room: 'Garden',
    status: 'active',
    age: 7,
    gender: 'M',
    spriteId: 'male09',
    stats:      { STR: 6, DEX: 14, CON: 5, INT: 6, SPD: 12, CHA: 5, LUCK: 11 },
    bonusStats: { STR: 0, DEX: 2,  CON: 0, INT: 0, SPD: 2,  CHA: 0, LUCK: 1  },
    abilities: ['ArrowRain', 'Track', 'Camouflage'],
    mutations: ['EagleEyes', 'SwiftPaws'],
  },
  {
    id: '10',
    name: 'Vex',
    class: 'Warlock',
    classLevel: 5,
    room: 'Crypt',
    status: 'retired',
    age: 18,
    gender: 'F',
    spriteId: 'female10',
    stats:      { STR: 4, DEX: 6, CON: 4, INT: 12, SPD: 5, CHA: 9, LUCK: 8 },
    bonusStats: { STR: 0, DEX: 0, CON: 0, INT: 2,  SPD: 0, CHA: 2, LUCK: 1 },
    abilities: ['Hex', 'SoulDrain', 'DarkPact'],
    mutations: ['HollowEyes', 'ShadowWings', 'PhaseShift'],
  },
  {
    id: '11',
    name: 'Cinder',
    class: 'Ranger',
    classLevel: 1,
    room: 'Garden',
    status: 'active',
    age: 3,
    gender: 'F',
    spriteId: 'female06',
    stats:      { STR: 8, DEX: 12, CON: 7, INT: 5, SPD: 10, CHA: 5, LUCK: 6 },
    bonusStats: { STR: 0, DEX: 1,  CON: 0, INT: 0, SPD: 1,  CHA: 0, LUCK: 0 },
    abilities: ['ArrowRain', 'FireArrow'],
    mutations: ['FlameFur', 'SwiftPaws'],
  },
  {
    id: '12',
    name: 'Mortis',
    class: 'Necromancer',
    classLevel: 4,
    room: 'Crypt',
    status: 'active',
    age: 11,
    gender: 'M',
    spriteId: 'male13',
    stats:      { STR: 3, DEX: 4, CON: 5, INT: 11, SPD: 4, CHA: 5, LUCK: 9 },
    bonusStats: { STR: 0, DEX: 0, CON: 0, INT: 2,  SPD: 0, CHA: 0, LUCK: 2 },
    abilities: ['RaiseDead', 'BoneSpear'],
    mutations: ['BoneClaws', 'GlowingEyes'],
  },
  {
    id: '13',
    name: 'Seraph',
    class: 'Cleric',
    classLevel: 3,
    room: 'Chapel',
    status: 'active',
    age: 5,
    gender: 'F',
    spriteId: 'female04',
    stats:      { STR: 5, DEX: 5, CON: 9, INT: 10, SPD: 5, CHA: 11, LUCK: 13 },
    bonusStats: { STR: 0, DEX: 0, CON: 1, INT: 1,  SPD: 0, CHA: 2,  LUCK: 2  },
    abilities: ['Heal', 'Smite'],
    mutations: ['AngelWings'],
  },
  {
    id: '14',
    name: 'Runt',
    class: 'Warrior',
    classLevel: 1,
    room: 'Barracks',
    status: 'active',
    age: 2,
    gender: 'M',
    spriteId: 'male05',
    stats:      { STR: 9, DEX: 7, CON: 8, INT: 3, SPD: 6, CHA: 4, LUCK: 5 },
    bonusStats: { STR: 1, DEX: 0, CON: 1, INT: 0, SPD: 0, CHA: 0, LUCK: 0 },
    abilities: ['Slash'],
    mutations: [],
  },
]

export const MOCK_ROOMS = [
  { id: 'library',  name: 'Library',  capacity: 4, cats: ['1', '3', '7'] },
  { id: 'barracks', name: 'Barracks', capacity: 5, cats: ['2', '6', '8', '14'] },
  { id: 'chapel',   name: 'Chapel',   capacity: 3, cats: ['4', '13'] },
  { id: 'crypt',    name: 'Crypt',    capacity: 4, cats: ['5', '10', '12'] },
  { id: 'garden',   name: 'Garden',   capacity: 4, cats: ['9', '11'] },
]
