export const MOCK_CATS = [
  {
    id: '1',
    name: 'Whiskers',
    class: 'Mage',
    room: 'Library',
    status: 'active',
    age: 12,
    stats: { STR: 3, DEX: 7, INT: 10, VIT: 5, LCK: 8 },
    abilities: ['Fireball', 'Blink'],
    mutations: ['Glowing Eyes', 'Extra Tail'],
    gender: 'F',
    color: '#a855f7',
  },
  {
    id: '2',
    name: 'Brutus',
    class: 'Warrior',
    room: 'Barracks',
    status: 'active',
    age: 6,
    stats: { STR: 12, DEX: 4, INT: 2, VIT: 11, LCK: 3 },
    abilities: ['Slash', 'Taunt'],
    mutations: ['Iron Fur'],
    gender: 'M',
    color: '#ef4444',
  },
  {
    id: '3',
    name: 'Shadow',
    class: 'Rogue',
    room: 'Library',
    status: 'retired',
    age: 20,
    stats: { STR: 6, DEX: 13, INT: 5, VIT: 4, LCK: 9 },
    abilities: ['Backstab', 'Smoke Bomb', 'Blink'],
    mutations: ['Glowing Eyes', 'Phase Shift'],
    gender: 'M',
    color: '#6366f1',
  },
  {
    id: '4',
    name: 'Luna',
    class: 'Cleric',
    room: 'Chapel',
    status: 'active',
    age: 8,
    stats: { STR: 4, DEX: 6, INT: 9, VIT: 8, LCK: 12 },
    abilities: ['Heal', 'Holy Light', 'Resurrect'],
    mutations: ['Angel Wings', 'Halo'],
    gender: 'F',
    color: '#fbbf24',
  },
  {
    id: '5',
    name: 'Grim',
    class: 'Necromancer',
    room: 'Crypt',
    status: 'active',
    age: 15,
    stats: { STR: 5, DEX: 5, INT: 13, VIT: 3, LCK: 6 },
    abilities: ['Raise Dead', 'Soul Drain', 'Curse'],
    mutations: ['Hollow Eyes', 'Bone Claws'],
    gender: 'M',
    color: '#10b981',
  },
  {
    id: '6',
    name: 'Patches',
    class: 'Rogue',
    room: 'Barracks',
    status: 'active',
    age: 4,
    stats: { STR: 7, DEX: 11, INT: 4, VIT: 6, LCK: 10 },
    abilities: ['Backstab', 'Pickpocket'],
    mutations: ['Phase Shift'],
    gender: 'F',
    color: '#f97316',
  },
  {
    id: '7',
    name: 'Ember',
    class: 'Mage',
    room: 'Library',
    status: 'dead',
    age: 25,
    stats: { STR: 2, DEX: 8, INT: 14, VIT: 2, LCK: 7 },
    abilities: ['Fireball', 'Meteor', 'Blink'],
    mutations: ['Glowing Eyes', 'Flame Fur', 'Extra Tail'],
    gender: 'F',
    color: '#a855f7',
  },
  {
    id: '8',
    name: 'Tank',
    class: 'Warrior',
    room: 'Barracks',
    status: 'active',
    age: 9,
    stats: { STR: 14, DEX: 2, INT: 1, VIT: 15, LCK: 2 },
    abilities: ['Shield Bash', 'Taunt', 'Fortify'],
    mutations: ['Iron Fur', 'Stone Skin'],
    gender: 'M',
    color: '#ef4444',
  },
  {
    id: '9',
    name: 'Zephyr',
    class: 'Ranger',
    room: 'Garden',
    status: 'active',
    age: 7,
    stats: { STR: 6, DEX: 14, INT: 6, VIT: 5, LCK: 11 },
    abilities: ['Arrow Rain', 'Track', 'Camouflage'],
    mutations: ['Eagle Eyes', 'Swift Paws'],
    gender: 'M',
    color: '#22d3ee',
  },
  {
    id: '10',
    name: 'Vex',
    class: 'Warlock',
    room: 'Crypt',
    status: 'retired',
    age: 18,
    stats: { STR: 4, DEX: 6, INT: 12, VIT: 4, LCK: 8 },
    abilities: ['Hex', 'Soul Drain', 'Dark Pact'],
    mutations: ['Hollow Eyes', 'Shadow Wings', 'Phase Shift'],
    gender: 'F',
    color: '#8b5cf6',
  },
  {
    id: '11',
    name: 'Cinder',
    class: 'Ranger',
    room: 'Garden',
    status: 'active',
    age: 3,
    stats: { STR: 8, DEX: 12, INT: 5, VIT: 7, LCK: 6 },
    abilities: ['Arrow Rain', 'Fire Arrow'],
    mutations: ['Flame Fur', 'Swift Paws'],
    gender: 'F',
    color: '#22d3ee',
  },
  {
    id: '12',
    name: 'Mortis',
    class: 'Necromancer',
    room: 'Crypt',
    status: 'active',
    age: 11,
    stats: { STR: 3, DEX: 4, INT: 11, VIT: 5, LCK: 9 },
    abilities: ['Raise Dead', 'Bone Spear'],
    mutations: ['Bone Claws', 'Glowing Eyes'],
    gender: 'M',
    color: '#10b981',
  },
  {
    id: '13',
    name: 'Seraph',
    class: 'Cleric',
    room: 'Chapel',
    status: 'active',
    age: 5,
    stats: { STR: 5, DEX: 5, INT: 10, VIT: 9, LCK: 13 },
    abilities: ['Heal', 'Smite'],
    mutations: ['Angel Wings'],
    gender: 'F',
    color: '#fbbf24',
  },
  {
    id: '14',
    name: 'Runt',
    class: 'Warrior',
    room: 'Barracks',
    status: 'active',
    age: 2,
    stats: { STR: 9, DEX: 7, INT: 3, VIT: 8, LCK: 5 },
    abilities: ['Slash'],
    mutations: [],
    gender: 'M',
    color: '#ef4444',
  },
]

export const MOCK_ROOMS = [
  { id: 'library', name: 'Library', capacity: 4, cats: ['1', '3', '7'] },
  { id: 'barracks', name: 'Barracks', capacity: 5, cats: ['2', '6', '8', '14'] },
  { id: 'chapel', name: 'Chapel', capacity: 3, cats: ['4', '13'] },
  { id: 'crypt', name: 'Crypt', capacity: 4, cats: ['5', '10', '12'] },
  { id: 'garden', name: 'Garden', capacity: 4, cats: ['9', '11'] },
]
